# HMAC signing key for approval-link tokens (remediation_common.approvals).
# Generated by Terraform once and stored in Secrets Manager rather than as
# a plaintext variable/parameter - request_approval and approval_callback
# both read it at runtime, and rotating it (manually, via the console or
# CLI) invalidates any outstanding approval links, which is the correct
# failure mode if the secret is ever suspected compromised.

resource "random_password" "approval_signing_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "approval_signing_secret" {
  # checkov:skip=CKV2_AWS_57: automatic rotation needs a rotation Lambda
  # that understands what "rotate" means for this secret's consumers
  # (both request_approval and approval_callback would need to accept two
  # valid signing keys during the overlap window). Not worth building for
  # a value with no external dependency on rotating it - manually
  # rotating it, documented above, is the deliberate approach.
  name                    = "${local.name_prefix}-approval-signing-secret"
  recovery_window_in_days = 7
  kms_key_id              = aws_kms_key.data.arn
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "approval_signing_secret" {
  secret_id     = aws_secretsmanager_secret.approval_signing_secret.id
  secret_string = random_password.approval_signing_secret.result
}
